CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id    INTEGER REFERENCES users (id) ON DELETE RESTRICT,
    name        VARCHAR(100),
    description VARCHAR(200),
    available   BOOLEAN,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    renter_id              INTEGER REFERENCES users (id) ON DELETE RESTRICT,
    item_id                INTEGER REFERENCES items (id) ON DELETE RESTRICT,
    booking_start_datetime TIMESTAMP,
    booking_end_datetime   TIMESTAMP,
    status                 VARCHAR(255),
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id       INTEGER REFERENCES items (id) ON DELETE RESTRICT,
    user_id       INTEGER REFERENCES users (id) ON DELETE RESTRICT,
    comment_text  VARCHAR(1000),
    creation_date TIMESTAMP,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

DELETE FROM comments;
DELETE FROM bookings;
DELETE FROM items;
DELETE FROM users;